apiVersion: v1
appVersion: 0.9.3
description: CoreOS etcd-operator Helm chart for Kubernetes (K8S v1.16+)
home: https://github.com/coreos/etcd-operator
icon: https://raw.githubusercontent.com/coreos/etcd/master/logos/etcd-horizontal-color.png
maintainers:
- email: lachlan@deis.com
  name: lachie83
- email: jaescobar.cell@gmail.com
  name: alejandroEsc
name: etcd-operator
sources:
- https://github.com/coreos/etcd-operator
version: 0.8.3-1.16
